import os
import logging
from telegram import Update
from telegram.ext import Application, CommandHandler, MessageHandler, filters, ContextTypes
from google import genai

logging.basicConfig(format="%(asctime)s - %(name)s - %(levelname)s - %(message)s", level=logging.INFO)

TELEGRAM_BOT_TOKEN = os.environ.get("TELEGRAM_BOT_TOKEN")
GEMINI_API_KEY = os.environ.get("GEMINI_API_KEY")

try:
    AUTHORIZED_USER_ID = int(os.environ.get("AUTHORIZED_USER_ID", "0"))
    except ValueError:
        AUTHORIZED_USER_ID = 0

        client = genai.Client(api_key=GEMINI_API_KEY)

        USER_MASTER_RESUME = ""

        def check_authorization(update: Update) -> bool:
            if not update.effective_user or update.effective_user.id != AUTHORIZED_USER_ID:
                    return False
                        return True

                        async def start(update: Update, context: ContextTypes.DEFAULT_TYPE):
                            if not check_authorization(update):
                                    return
                                        await update.message.reply_text(
                                                "🤖 **Job Application Agent Online!**\n\n"
                                                        "Step 1: Send me your master resume text first by typing: /setresume [Paste your resume here]\n"
                                                                "Step 2: After that, paste any job description from a career page, and I will calculate your match score and tailor your resume!"
                                                                    )

                                                                    async def set_resume(update: Update, context: ContextTypes.DEFAULT_TYPE):
                                                                        if not check_authorization(update):
                                                                                return
                                                                                    global USER_MASTER_RESUME
                                                                                        text_parts = update.message.text.split(" ", 1)
                                                                                            if len(text_parts) > 1:
                                                                                                    USER_MASTER_RESUME = text_parts[1]
                                                                                                            await update.message.reply_text("✅ Master resume saved successfully! Now paste any job description.")
                                                                                                                else:
                                                                                                                        await update.message.reply_text("❌ Please include your resume text after the command. Example: /setresume Software Engineer with 3 years experience...")

                                                                                                                        async def handle_job_flow(update: Update, context: ContextTypes.DEFAULT_TYPE):
                                                                                                                            if not check_authorization(update):
                                                                                                                                    return
                                                                                                                                            import os
                                                                                                                                            import logging
                                                                                                                                            from telegram import Update
                                                                                                                                            from telegram.ext import Application, CommandHandler, MessageHandler, filters, ContextTypes
                                                                                                                                            from google import genai

                                                                                                                                            logging.basicConfig(format="%(asctime)s - %(name)s - %(levelname)s - %(message)s", level=logging.INFO)

                                                                                                                                            TELEGRAM_BOT_TOKEN = os.environ.get("TELEGRAM_BOT_TOKEN")
                                                                                                                                            GEMINI_API_KEY = os.environ.get("GEMINI_API_KEY")

                                                                                                                                            try:
                                                                                                                                                AUTHORIZED_USER_ID = int(os.environ.get("AUTHORIZED_USER_ID", "0"))
                                                                                                                                                except ValueError:
                                                                                                                                                    AUTHORIZED_USER_ID = 0

                                                                                                                                                    client = genai.Client(api_key=GEMINI_API_KEY)

                                                                                                                                                    USER_MASTER_RESUME = ""

                                                                                                                                                    def check_authorization(update: Update) -> bool:
                                                                                                                                                        if not update.effective_user or update.effective_user.id != AUTHORIZED_USER_ID:
                                                                                                                                                                return False
                                                                                                                                                                    return True

                                                                                                                                                                    async def start(update: Update, context: ContextTypes.DEFAULT_TYPE):
                                                                                                                                                                        if not check_authorization(update):
                                                                                                                                                                                return
                                                                                                                                                                                    await update.message.reply_text(
                                                                                                                                                                                            "🤖 **Job Application Agent Online!**\n\n"
                                                                                                                                                                                                    "Step 1: Send me your master resume text first by typing: /setresume [Paste your resume here]\n"
                                                                                                                                                                                                            "Step 2: After that, paste any job description from a career page, and I will calculate your match score and tailor your resume!"
                                                                                                                                                                                                                )

                                                                                                                                                                                                                async def set_resume(update: Update, context: ContextTypes.DEFAULT_TYPE):
                                                                                                                                                                                                                    if not check_authorization(update):
                                                                                                                                                                                                                            return
                                                                                                                                                                                                                                global USER_MASTER_RESUME
                                                                                                                                                                                                                                    text_parts = update.message.text.split(" ", 1)
                                                                                                                                                                                                                                        if len(text_parts) > 1:
                                                                                                                                                                                                                                                USER_MASTER_RESUME = text_parts[1]
                                                                                                                                                                                                                                                        await update.message.reply_text("✅ Master resume saved successfully! Now paste any job description.")
                                                                                                                                                                                                                                                            else:
                                                                                                                                                                                                                                                                    await update.message.reply_text("❌ Please include your resume text after the command. Example: /setresume Software Engineer with 3 years experience...")

                                                                                                                                                                                                                                                                    async def handle_job_flow(update: Update, context: ContextTypes.DEFAULT_TYPE):
                                                                                                                                                                                                                                                                        if not check_authorization(update):
                                                                                                                                                                                                                                                                                return
                                                                                                                                                                                                                                                                                        
                                                                                                                                                                                                                                                                                            global USER_MASTER_RESUME
                                                                                                                                                                                                                                                                                                if not USER_MASTER_RESUME:
                                                                                                                                                                                                                                                                                                        await update.message.reply_text("⚠️ Please save your master resume first using the `/setresume` command!")
                                                                                                                                                                                                                                                                                                                return

                                                                                                                                                                                                                                                                                                                    job_text = update.message.text
                                                                                                                                                                                                                                                                                                                        await update.message.reply_text("🔍 Analyzing job description against your master resume...")

                                                                                                                                                                                                                                                                                                                            prompt = f"""
                                                                                                                                                                                                                                                                                                                                You are an elite technical career coach and ATS resume architect.
                                                                                                                                                                                                                                                                                                                                    
                                                                                                                                                                                                                                                                                                                                        MY MASTER RESUME:
                                                                                                                                                                                                                                                                                                                                            {USER_MASTER_RESUME}
                                                                                                                                                                                                                                                                                                                                                
                                                                                                                                                                                                                                                                                                                                                    JOB DESCRIPTION TO TARGET:
                                                                                                                                                                                                                                                                                                                                                        {job_text}

                                                                                                                                                                                                                                                                                                                                                            Task:
                                                                                                                                                                                                                                                                                                                                                                1. Provide a Match Score (out of 100%).
                                                                                                                                                                                                                                                                                                                                                                    2. List missing keywords or skills.
                                                                                                                                                                                                                                                                                                                                                                        3. Rewrite my professional summary and top 3 experience bullets *specifically tailored* to match this job description using my master resume history.
                                                                                                                                                                                                                                                                                                                                                                            """

                                                                                                                                                                                                                                                                                                                                                                                try:
                                                                                                                                                                                                                                                                                                                                                                                        response = client.models.generate_content(
                                                                                                                                                                                                                                                                                                                                                                                                    model="gemini-2.5-flash",
                                                                                                                                                                                                                                                                                                                                                                                                                contents=prompt,
                                                                                                                                                                                                                                                                                                                                                                                                                        )
                                                                                                                                                                                                                                                                                                                                                                                                                                await update.message.reply_text(
                                                                                                                                                                                                                                                                                                                                                                                                                                            f"📊 **Job Match & Tailored Resume Ready!**\n\n{response.text}\n\n"
                                                                                                                                                                                                                                                                                                                                                                                                                                                        "*(Copy the tailored text above to submit for your application!)*"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                )
                                                                                                                                                                                                                                                                                                                                                                                                                                                                    except Exception as e:
                                                                                                                                                                                                                                                                                                                                                                                                                                                                            await update.message.reply_text(f"❌ Error: {str(e)}")

                                                                                                                                                                                                                                                                                                                                                                                                                                                                            def main():
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                if not TELEGRAM_BOT_TOKEN or not GEMINI_API_KEY or AUTHORIZED_USER_ID == 0:
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        print("CRITICAL ERROR: Missing environment variables.")
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                return

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    application = Application.builder().token(TELEGRAM_BOT_TOKEN).build()

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        application.add_handler(CommandHandler("start", start))
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            application.add_handler(CommandHandler("setresume", set_resume))
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                application.add_handler(MessageHandler(filters.TEXT & ~filters.COMMAND, handle_job_flow))

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    print("Bot is starting polling loop...")
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        application.run_polling(drop_pending_updates=True)

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        if __name__ == "__main__":
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            main()
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            
                                                                                                                                                global USER_MASTER_RESUME
                                                                                                                                                    if not USER_MASTER_RESUME:
                                                                                                                                                            await update.message.reply_text("⚠️ Please save your master resume first using the `/setresume` command!")
                                                                                                                                                                    return

                                                                                                                                                                        job_text = update.message.text
                                                                                                                                                                            await update.message.reply_text("🔍 Analyzing job description against your master resume...")

                                                                                                                                                                                prompt = f"""
                                                                                                                                                                                    You are an elite technical career coach and ATS resume architect.
                                                                                                                                                                                        
                                                                                                                                                                                            MY MASTER RESUME:
                                                                                                                                                                                                {USER_MASTER_RESUME}
                                                                                                                                                                                                    
                                                                                                                                                                                                        JOB DESCRIPTION TO TARGET:
                                                                                                                                                                                                            {job_text}

                                                                                                                                                                                                                Task:
                                                                                                                                                                                                                    1. Provide a Match Score (out of 100%).
                                                                                                                                                                                                                        2. List missing keywords or skills.
                                                                                                                                                                                                                            3. Rewrite my professional summary and top 3 experience bullets *specifically tailored* to match this job description using my master resume history.
                                                                                                                                                                                                                                """

                                                                                                                                                                                                                                    try:
                                                                                                                                                                                                                                            response = client.models.generate_content(
                                                                                                                                                                                                                                                        model="gemini-2.5-flash",
                                                                                                                                                                                                                                                                    contents=prompt,
                                                                                                                                                                                                                                                                            )
                                                                                                                                                                                                                                                                                    await update.message.reply_text(
                                                                                                                                                                                                                                                                                                f"📊 **Job Match & Tailored Resume Ready!**\n\n{response.text}\n\n"
                                                                                                                                                                                                                                                                                                            "*(Copy the tailored text above to submit for your application!)*"
                                                                                                                                                                                                                                                                                                                    )
                                                                                                                                                                                                                                                                                                                        except Exception as e:
                                                                                                                                                                                                                                                                                                                                await update.message.reply_text(f"❌ Error: {str(e)}")

                                                                                                                                                                                                                                                                                                                                def main():
                                                                                                                                                                                                                                                                                                                                    if not TELEGRAM_BOT_TOKEN or not GEMINI_API_KEY or AUTHORIZED_USER_ID == 0:
                                                                                                                                                                                                                                                                                                                                            print("CRITICAL ERROR: Missing environment variables.")
                                                                                                                                                                                                                                                                                                                                                    return

                                                                                                                                                                                                                                                                                                                                                        application = Application.builder().token(TELEGRAM_BOT_TOKEN).build()

                                                                                                                                                                                                                                                                                                                                                            application.add_handler(CommandHandler("start", start))
                                                                                                                                                                                                                                                                                                                                                                application.add_handler(CommandHandler("setresume", set_resume))
                                                                                                                                                                                                                                                                                                                                                                    application.add_handler(MessageHandler(filters.TEXT & ~filters.COMMAND, handle_job_flow))

                                                                                                                                                                                                                                                                                                                                                                        print("Bot is starting polling loop...")
                                                                                                                                                                                                                                                                                                                                                                            application.run_polling(drop_pending_updates=True)

                                                                                                                                                                                                                                                                                                                                                                            if __name__ == "__main__":
                                                                                                                                                                                                                                                                                                                                                                                main()
